### ISSUE TITLE
`enhancement`  

### ISSUE THREAD

**Issue by ORCA666** [maxpl0it/crackme101#1]
i do some simple patching on crackmes, we can make this repo bigger if u wanted, take a look at this 
https://github.com/ORCA666/patched-files
:)

**Comment by maxpl0it** [comment]
Hey, feel free to add mine in there!

**Comment by ORCA666** [comment]
> Hey, feel free to add mine in there!

i actually meant you to add mine, cz this repo got more stars / forks than mine 🤷‍♂️🤷‍♂️

**Comment by maxpl0it** [comment]
Ah, my bad!
Unfortunately this isn't a repo of third party challenges, it's an internal crackme training I put together and ran for F-Secure which I then released publicly in case anyone externally was interested

**Comment by ORCA666** [comment]
Oh, I hit you , well never mind, sorry for bothering !

**Comment by maxpl0it** [comment]
No worries, good luck with your repo!
